// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WebHi {
	
	
	public partial class Common {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder head;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder htmlBody;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder jsWrap;
	}
}
